include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

  exclude: [lib/**.freezed.dart, lib/**.g.dart]

errors:
  require_trailing_commas: warning

linter:
  rules:
    - require_trailing_commas
    - prefer_single_quotes
    - prefer_final_locals
    - avoid_redundant_argument_values
    - directives_ordering
    - avoid_classes_with_only_static_members
    - avoid_escaping_inner_quotes
    - unnecessary_parenthesis
    - prefer_interpolation_to_compose_strings
    - only_throw_errors
    - avoid_positional_boolean_parameters
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - unawaited_futures
    - unnecessary_await_in_return
    - discarded_futures
    - avoid_void_async
