// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwoRpOo78hWZwO-rHL7GXBUFEERbPr8A0',
    appId: '1:150599422814:web:00acdc54ddfa0e10c7f5cf',
    messagingSenderId: '150599422814',
    projectId: 'dante-166506',
    authDomain: 'dante-166506.firebaseapp.com',
    databaseURL: 'https://dante-166506.firebaseio.com',
    storageBucket: 'dante-166506.appspot.com',
    measurementId: 'G-9BTBKSQ8TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtvxhSPEmpatfwdCRk3Og83eKAcDWQ5g',
    appId: '1:150599422814:android:dc5fc2c358c1c3c7c7f5cf',
    messagingSenderId: '150599422814',
    projectId: 'dante-166506',
    databaseURL: 'https://dante-166506.firebaseio.com',
    storageBucket: 'dante-166506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7PlDiSTF7b55InzW5rSaPExNrvczZHY',
    appId: '1:150599422814:ios:cd220b909b2c0d51c7f5cf',
    messagingSenderId: '150599422814',
    projectId: 'dante-166506',
    databaseURL: 'https://dante-166506.firebaseio.com',
    storageBucket: 'dante-166506.appspot.com',
    androidClientId:
        '150599422814-d66dntqhg58fins21hfj96eu6v1p9vgt.apps.googleusercontent.com',
    iosClientId:
        '150599422814-eorssa86b5b5l2p2h4ri8bhg82jqsovj.apps.googleusercontent.com',
    iosBundleId: 'at.shockbytes.dantex',
  );
}
